"""add a description to the comments table

Revision ID: 087e19de8ddd
Revises: 734ea5a6ad31
Create Date: 2019-09-23 13:30:36.152919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087e19de8ddd'
down_revision = '734ea5a6ad31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'description')
    # ### end Alembic commands ###
