"""add an authors column to blogs table

Revision ID: 0c4798ecbb9c
Revises: 18382abc081e
Create Date: 2019-09-23 11:41:21.831807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4798ecbb9c'
down_revision = '18382abc081e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bloggs', sa.Column('author', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bloggs', 'author')
    # ### end Alembic commands ###
