"""add a blogs table

Revision ID: 18382abc081e
Revises: 9b522555ab7e
Create Date: 2019-09-23 11:15:58.878978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18382abc081e'
down_revision = '9b522555ab7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloggs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('blog_content', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bloggs_blog_content'), 'bloggs', ['blog_content'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bloggs_blog_content'), table_name='bloggs')
    op.drop_table('bloggs')
    # ### end Alembic commands ###
